### ISSUE TITLE
'NoneType' object has no attribute 'filename'

### ISSUE THREAD

**Issue by matildepark** [furudean/vscode-renpy-warp#93]
This started on my macOS instance after updating to 15.5? 

If I click "Warp to line," RenPy crashes, as though we're not feeding it the file. Happened in VSCodium, but then I went back to VS Code where it used to work and it does not now. This extension does still work as usual in Linux, so intriguing to me.

Using RenPy 8.2.3.

<img width="1392" alt="Image" src="https://github.com/user-attachments/assets/ceaf1467-e230-4480-ac2a-cd01f60f4bef" />

The logs look similar:

```
process 40351 started
INFO:renpy_warp_service:service thread started. periodically scanning ports for warp server

Full traceback:
  File "renpy/common/00start.rpy", line 213, in script
    python hide:
  File "/Users/maru/Documents/renpy-8.2.3-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/maru/Documents/renpy-8.2.3-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 213, in <module>
    python hide:
  File "renpy/common/00start.rpy", line 214, in _execute_python_hide
    renpy.warp.warp()
  File "/Users/maru/Documents/renpy-8.2.3-sdk/renpy/warp.py", line 130, in warp
    add(n, n.get_next())
  File "/Users/maru/Documents/renpy-8.2.3-sdk/renpy/warp.py", line 91, in add
    n = n or prefer(lambda a, b : (a.filename == next.filename) and (b.filename != next.filename))
  File "/Users/maru/Documents/renpy-8.2.3-sdk/renpy/warp.py", line 82, in prefer
    if fn(node, old):
  File "/Users/maru/Documents/renpy-8.2.3-sdk/renpy/warp.py", line 91, in <lambda>
    n = n or prefer(lambda a, b : (a.filename == next.filename) and (b.filename != next.filename))
AttributeError: 'NoneType' object has no attribute 'filename'

While running game code:
  File "renpy/common/00start.rpy", line 213, in script
    python hide:
  File "renpy/common/00start.rpy", line 213, in <module>
    python hide:
  File "renpy/common/00start.rpy", line 214, in _execute_python_hide
    renpy.warp.warp()
AttributeError: 'NoneType' object has no attribute 'filename'
INFO:renpy_warp_service:connected to renpy warp socket server on :40111
INFO:renpy_warp_service:closing websocket connection :40111
INFO:renpy_warp_service:connection replaced, service exiting
INFO:renpy_warp_service:service closed
process exited with code 1
```

Any pointers?

**Comment by furudean** [comment]
Can you set the `renpyWarp.processEnvironment` setting to `{ "WARP_LOGLEVEL": "DEBUG" }` and tell me what you get in your console?

**Comment by matildepark** [comment]
```
DEBUG:renpy_warp_service:sent message: {"type": "list_labels", "labels": ["_after_warp", "_start_replay", "skip_credits", "after_load", "load_screen", "_gl_test", "_style_reset", "_game_menu_load", "_return", "_developer", "ch1", "ch2", "splashscreen", "credits", "main_menu_screen", "_call__load_reload_game_1", "_filename_list", "_return_skipping", "_quit_prompt", "_enter_game_menu", "_image_location_picker", "joystick_preferences_screen", "_hide_windows", "_invoke_main_menu", "_start", "save_screen", "_variable_viewer", "_quit", "_console_return", "_image_attributes", "ch2d6", "ch2d7", "ch2d4", "ch2d5", "_choose_renderer", "ch2d2", "ch2d3", "_noisy_return", "_renpy_return", "_start_store", "set_gui_color", "ch2d8", "_game_menu_save", "_call__enter_game_menu_3", "_call__enter_game_menu_2", "_call__enter_game_menu_1", "_call__enter_game_menu_0", "_game_menu_preferences", "_splashscreen", "_call_splashscreen_1", "ch1d2", "ch1d3", "ch1d4", "ch1d6", "ch1d7", "ch1d8", "preferences_screen", "_save_reload_game", "_load_reload_game", "_after_load", "_return_fast_skipping", "_console", "ch1d5", "_game_menu", "_errorhandling", "_main_menu", "_main_menu_screen", "start", "_confirm_quit", "_main_menu_prompt", "_call_enter_game_menu_1", "_image_location_picker_done", "skip_splash", "_persistent_viewer"]}
```

**Comment by furudean** [comment]
What about running `renpy.warp_to_line('<file>:<line>')` in your Renpy console (ctrl+o)? Does that work?

**Comment by matildepark** [comment]
No, it's unrelated and my fault. I stepped through with Git and the commit that started this behaviour was when I introduced a few layeredimages in the main menu; making them an image of some fixed transforms stops it from choking. No, for real.

**Comment by furudean** [comment]
Happens to the best of us
